(ert-deftest describe-commit ()
  (with-temp-dir path
    (init)
    (commit-change "a" "abc")
    (run "git" "tag" "-a" "v1" "-m" "v1")
    (let* ((repo (libgit2-repository-open path))
           (commit (libgit2-revparse-single repo "HEAD"))
           (id (libgit2-object-id commit)))
      (should (string= (libgit2-describe-commit commit) "v1"))
      (should (string= (libgit2-describe-commit commit '((always-use-long-format . t)))
                       (concat "v1-0-g" (substring id 0 7)))))
    (commit-change "b" "abc")
    (let* ((repo (libgit2-repository-open path))
           (commit (libgit2-revparse-single repo "HEAD"))
           (id (libgit2-object-id commit)))
      (should (string= (libgit2-describe-commit commit)
                       (concat "v1-1-g" (substring id 0 7))))
      (should (string= (libgit2-describe-commit commit '((strategy . all))) "heads/master")))))

(ert-deftest describe-workdir ()
  (with-temp-dir path
    (init)
    (commit-change "a" "abc")
    (run "git" "tag" "-a" "v1" "-m" "v1")
    (let* ((repo (libgit2-repository-open path))
           (id (libgit2-reference-name-to-id repo "HEAD")))
      (should (string= (libgit2-describe-workdir repo) "v1"))
      (should (string= (libgit2-describe-workdir repo '((always-use-long-format . t)))
                       (concat "v1-0-g" (substring id 0 7)))))
    (write "a" "xyz")
    (let* ((repo (libgit2-repository-open path))
           (id (libgit2-reference-name-to-id repo "HEAD")))
      (should (string= (libgit2-describe-workdir repo) "v1"))
      (should (string= (libgit2-describe-workdir repo '((always-use-long-format . t)))
                       (concat "v1-0-g" (substring id 0 7))))
      (should (string= (libgit2-describe-workdir repo '((dirty-suffix . "*"))) "v1*"))
      (should (string= (libgit2-describe-workdir repo '((always-use-long-format . t)
                                                       (dirty-suffix . "---")))
                       (concat "v1-0-g" (substring id 0 7) "---"))))))
