README.rst: README.in.rst libgit2.el
	grep ';;' libgit2.el \
	  | awk '/;;;\s*Commentary/{within=1;next}/;;;\s*/{within=0}within' \
	  | sed -e 's/^\s*;;*\s*//g' \
	  | bash readme-sed.sh "COMMENTARY" README.in.rst > README.rst
